repos:
  - repo: local
    hooks:
      - id: format-public-api
        name: Format public_api
        entry: bash -c 'cd public_api && poetry run format'
        language: system
        files: ^public_api/
        types: [python]
        pass_filenames: false

      - id: lint-public-api
        name: Lint public_api
        entry: bash -c 'cd public_api && poetry run lint'
        language: system
        files: ^public_api/
        types: [python]
        pass_filenames: false
